// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SweDemoBackend.Infrastructure.Migrations
{
    [DbContext(typeof(BricksForKidsDbContext))]
    partial class BricksForKidsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SweDemoBackend.Domain.Entities.LegoSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPieces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LegoSet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3c73d8d-5f8a-4f2a-9c11-2c9a1c2f8d2e"),
                            Name = "Harry Potter Zweinstein",
                            NumberOfPieces = 1540
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
